// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD40xpSbJD6UoAleUOnwM3AoE0R4gIeI-s',
    appId: '1:893233862104:web:38002fc6d4e3efbbf68ead',
    messagingSenderId: '893233862104',
    projectId: 'unisports-271ec',
    authDomain: 'unisports-271ec.firebaseapp.com',
    storageBucket: 'unisports-271ec.firebasestorage.app',
    measurementId: 'G-T6WZPMTFSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdL35E6SIUSWss3NiDqDMtD3IRWx8C9Ng',
    appId: '1:893233862104:android:8ff44de39acc3863f68ead',
    messagingSenderId: '893233862104',
    projectId: 'unisports-271ec',
    storageBucket: 'unisports-271ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_a5A_eBrf8cpJ7Ytf-_WaCH7WTE7cw9Q',
    appId: '1:893233862104:ios:d4255026366b81a1f68ead',
    messagingSenderId: '893233862104',
    projectId: 'unisports-271ec',
    storageBucket: 'unisports-271ec.firebasestorage.app',
    iosBundleId: 'com.example.uniSports',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_a5A_eBrf8cpJ7Ytf-_WaCH7WTE7cw9Q',
    appId: '1:893233862104:ios:d4255026366b81a1f68ead',
    messagingSenderId: '893233862104',
    projectId: 'unisports-271ec',
    storageBucket: 'unisports-271ec.firebasestorage.app',
    iosBundleId: 'com.example.uniSports',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD40xpSbJD6UoAleUOnwM3AoE0R4gIeI-s',
    appId: '1:893233862104:web:0ce477575fc6fe9cf68ead',
    messagingSenderId: '893233862104',
    projectId: 'unisports-271ec',
    authDomain: 'unisports-271ec.firebaseapp.com',
    storageBucket: 'unisports-271ec.firebasestorage.app',
    measurementId: 'G-BB4DKRDLJJ',
  );

}